kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: yadagedata
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10G
  storageClassName: geneva-cephfs-testing

