apiVersion: yadage.github.io/v1
kind: Workflow
metadata:
  name: myflow
spec:
  initdata:
    input_mc16a: 'signal/mc16_13TeV.304123.MadGraphPythia8EvtGen_A14NNPDF23LO_zp2hdm_bb_mzp1400_mA600.deriv.DAOD_EXOT27.e4429_s3126_r9364_p3714.txt'
    input_mc16d: 'signal/mc16_13TeV.304123.MadGraphPythia8EvtGen_A14NNPDF23LO_zp2hdm_bb_mzp1400_mA600.deriv.DAOD_EXOT27.e4429_s3126_r10201_p3714.txt'
    dsid: '304123'
    nevents: '100'  # put -1 to run over all events
    lumi_mc16a: '36.21465331125'
    lumi_mc16d: '43.5934630485'
    xsecpb: '0.003746'
    PRW_mc16a: 'prw/pileup_mc16a_dsid310775_FS.root'
    PRW_mc16d: 'prw/pileup_mc16d_dsid310775_FS.root'
    PRW_mc16e: 'prw/pileup_mc16e_dsid310775_FS.root'
    limit_backgrounds: 'root://eosuser.cern.ch//eos/project/r/recast/atlas/ATLAS-CONF-2018-039/background/'
    limit_backgrounds_version: 'MonoH_0700_exocirculation_2018-06-24'
  toplevel: gitlab-cern:pgadow/recast-monohbb
  workflow: specs/workflow.yml
  dataarg: recast-flow-006
  dataopts:
    inputarchive: https://gitlab.cern.ch/api/v4/projects/pgadow%2Frecast-monohbb/repository/archive.zip?sha=master
    archivematch: '*/test/'
