apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: {{ .Values.job_namespace }}
spec:
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
      - image: python:alpine
        name: barectr
        workingDir: /srv
        command:
        - sh
        - -c
        - python -m http.server
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: data
          mountPath: /srv
      - image: python:alpine
        name: filebrower
        workingDir: /srv
        command:
        - sh
        - -c
        - |
          pip install sauth
          sauth {{ .Values.filebrowser_user }} {{ .Values.filebrowser_password }} 0.0.0.0 80
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /srv
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.claim_name }}
---
kind: Service
apiVersion: v1
metadata:
  name: filebrowser
  namespace: {{ .Values.job_namespace }} # comment: this must be the namespace of the job since the PV of the jobs must be accessible here
spec:
  type: NodePort
  selector:
    app: filebrowser
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
---
kind: Service
apiVersion: v1
metadata:
  name: fileaccess
  namespace: {{ .Values.job_namespace }} # comment: this must be the namespace of the job since the PV of the jobs must be accessible here
spec:
  selector:
    app: filebrowser
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
