# Helm being weird about namespaces
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: yadage
# ---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wflow-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wflow-controller
  template:
    metadata:
      labels:
        app: wflow-controller
    spec:
      containers:
      - name: controller
        image: {{ .Values.crdctrl.image }}
        imagePullPolicy: {{ .Values.crdctrl.pull_policy }}
        env:
        - name: YADKUBE_IMAGE
          value: {{ .Values.yadage.image }}
        - name: YADKUBE_IMAGE_POLICY
          value: {{ .Values.yadage.pull_policy }}
        - name: YADKUBE_CLAIM
          value: {{ .Values.storage.claim_name }}
        - name: YADKUBE_PRIVATE_TOKEN
          value: {{ .Values.private_token }}
        - name: YADKUBE_CPU_REQUEST
          value: {{ .Values.engine_cpu_request }}
        - name: YADKUBE_AUTH_SECRET
          value: hepauth
        - name: YADKUBE_REGCRED_SECRET
          value: hepimgcred
        - name: YADKUBE_RESOURCE_OPTS
          value: '{{ .Values.job.resource_opts | toJson }}'
---
apiVersion: v1
kind: Service
metadata:
  name: wflow-controller
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: wflow-controller
  ports:
  - port: 80

