# Helm being weird about namespaces
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: yadage
# ---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wflow-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wflow-controller
  template:
    metadata:
      labels:
        app: wflow-controller
    spec:
      containers:
      - name: controller
        image: {{ .Values.crdctrl_image }}
        imagePullPolicy: IfNotPresent
        env:
        - name: YADKUBE_IMAGE
          value: {{ .Values.yadage_image }}
        - name: YADKUBE_IMAGE_POLICY
          value: IfNotPresent
        - name: YADKUBE_CLAIM
          value: {{ .Values.claim_name }}
        - name: YADKUBE_PRIVATE_TOKEN
          value: {{ .Values.private_token }}
        - name: YADKUBE_AUTH_SECRET
          value: hepauth
        - name: YADKUBE_REGCRED_SECRET
          value: hepimgcred
---
apiVersion: v1
kind: Service
metadata:
  name: wflow-controller
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: wflow-controller
  ports:
  - port: 80

