apiVersion: v1
data: {"getkrb.sh": {{(printf "echo '%s'|kinit %s@CERN.CH" .Values.secrets.password .Values.secrets.username)|b64enc}} }
kind: Secret
metadata:
  name: hepauth
  namespace: default
type: Opaque
---

{{- define "imagePullSecret" }}
{{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.imageCredentials.registry (printf "%s:%s" .Values.imageCredentials.username .Values.imageCredentials.password | b64enc) | b64enc }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: myregistrykey
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
